const english = {
  lang: 'en',
  vacabluary: {
    newGame: 'New Game',
    options: 'Options',
    bestSore: 'Best Score',
    about: 'About',
    loading: 'Loading',
    finish: 'Finish',
    resume: 'Resume',
    save: 'SAVE',
    name: 'Name',
    time: 'Time',
    date: 'Date',
    score: 'Score',
    volume: 'Volume',
    fullScreen: 'Fullscreen',
    language: 'Language',
    back: 'Back',
    up: 'UP',
    down: 'DOWN',
    left: 'LEFT',
    right: 'RIGHT',
    KNIFE: 'KNIFE',
    PISTOL: 'PISTOL',
    SHORTGUN: 'SHORTGUN',
    RIFLE: 'RIFLE',
    run: 'RUN',
    weapon: 'WEAPON',
    aboutText: 'Stay alive as long as possible and go for the height score. \n Fight your way through and collect weapons and health.',
    chooseTheme: 'Choose the game theme',
    darkTheme: 'Dark',
    lightTheme: 'Light',
  },
};

export default english;
