const english = {
  lang: 'en',
  vacabluary: {
    // main
    newGame: 'New Game',
    options: 'Options',
    bestSore: 'Results',
    about: 'About',
    loadingState: 'LOADING',
    finishState: 'FINISH',
    resumeState: 'RESUME',
    pauseState: 'PAUSE',
    nameTitle: 'Name',
    timeTitle: 'Time',
    dateTitle: 'Date',
    scoreTitle: 'Score',
    healthTitle: 'Health',
    volume: 'Volume',
    fullScreen: 'Fullscreen',
    language: 'Language',
    back: 'Back',
    // about
    up: 'UP',
    down: 'DOWN',
    left: 'LEFT',
    right: 'RIGHT',
    KNIFE: 'KNIFE',
    PISTOL: 'PISTOL',
    SHORTGUN: 'SHORTGUN',
    RIFLE: 'RIFLE',
    run: 'RUN',
    weapon: 'WEAPON',
    aboutText1: 'Stay alive as long as possible and go for the height score.',
    aboutText2: 'Fight your way through and collect weapons and health.',
    chooseTheme: 'Choose the game theme',
    darkTheme: 'Dark',
    lightTheme: 'Light',
    // gameOver
    gameOverState: 'GAME OVER',
    save: 'SAVE',
    gameOverText: 'Enter your name to save a result',
    mainMenu: 'Main Menu',
  },
};

export default english;
