const russian = {
  lang: 'ru',
  vacabluary: {
    newGame: 'Новая игра',
    options: 'Опции',
    bestSore: 'Лучшие результаты',
    about: 'Об Игре',
    loadingState: 'ЗАГРУЗКА',
    finishState: 'ЗAКОНЧИТЬ',
    pauseState: 'ПАУЗА',
    resumeState: 'ВОЗОБНОВИТЬ',
    nameTitle: 'Имя',
    timeTitle: 'Время',
    dateTitle: 'Дата',
    scoreTitle: 'Очки',
    healthTitle: 'Здоровье',
    volume: 'Громкость',
    fullScreen: 'Полный экран',
    language: 'Язык',
    back: 'Назад',
    // about
    up: 'ВВЕРХ',
    down: 'ВНИЗ',
    left: 'ВЛЕВО',
    right: 'ВПРАВО',
    KNIFE: 'НОЖ',
    PISTOL: 'ПИСТОЛЕТ',
    SHORTGUN: 'ДРОБОВИК',
    RIFLE: 'ВИНТОВКА',
    run: 'БЕЖАТЬ',
    weapon: 'ОРУЖИЕ',
    aboutText1: 'Оставайтесь живым как можно дольше, для достижения наилучшего результата.',
    aboutText2: 'Срaжайтесь с врагами и собирайте оружие и здоровье.',
    chooseTheme: 'Выберите тему для игры',
    darkTheme: 'Tемная',
    lightTheme: 'Светлая',
    // gameOver
    gameOverState: 'Игра Закончена',
    save: 'СОХРАНИТЬ',
    gameOverText: 'Введите Ваше имя, чтобы сохранить результат',
  },
};

export default russian;
