const russian = {
  lang: 'ru',
  vacabluary: {
    newGame: 'Новая игра',
    options: 'Опции',
    bestSore: 'Лучшие результаты',
    about: 'Об Игре',
    loading: 'Загрузка',
    finish: 'Закончить',
    resume: 'Возобновить',
    save: 'Сохранить',
    name: 'Имя',
    time: 'Время',
    date: 'Дата',
    score: 'Очки',
    volume: 'Громкость',
    fullScreen: 'Полный экран',
    language: 'Язык',
    back: 'Назад',
    up: 'ВВЕРХ',
    down: 'ВНИЗ',
    left: 'ВЛЕВО',
    right: 'ВПРАВО',
    KNIFE: 'НОЖ',
    PISTOL: 'ПИСТОЛЕТ',
    SHORTGUN: 'ДРОБОВИК',
    RIFLE: 'ВИНТОВКА',
    run: 'БЕЖАТЬ',
    weapon: 'ОРУЖИЕ',
    aboutText: 'Оставайтесь живым как можно дольше, для достижения наилучшего результата. \n Срaжайтесь с врагами и собирайте оружие и здоровье.',
    chooseTheme: 'Выберите тему для игры',
    darkTheme: 'Tемная',
    lightTheme: 'Светлая',
  },
};

export default russian;
